apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/myproject-0000-crezencyo/locations/us-central1-c/clusters/dev-cluster

